export const ACTION_TEST_PENGDING = 'ACTION_TEST_PENGDING'
export const ACTION_TEST_FULFILLED = 'ACTION_TEST_FULFILLED'
export const ACTION_TEST_REJECTED = 'ACTION_TEST_REJECTED'
export const ACTION_TEST_REMOVED = 'ACTION_TEST_REMOVED'
